# -*- coding: utf-8 -*-
"""Feature_Engagement_Scorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lW-iW1CZ39a9akTbaQmcjnmqDCoVE-A
"""

import streamlit as st

st.title('App Feature Engagement Scorer')
st.write('A simple app to show how "Sticky" a feature is based on how often its used')

# Variable Inputs
total_logins = st.number_input('Enter the number of total logins', min_value=0,value=0,step=1)
feature_uses = st.number_input('Enter the number of feature uses', min_value=0,value=0,step=1)

if total_logins == 0:
  if feature_uses > 0:
    st.error('Wait a minute ! Auser cant use a feature without logging in. Check the data')
  else:
    st.warning('No logins recorded. User is completely inactive.')
elif feature_uses > total_logins:
  st.error("Data error: Feature uses cannot be greater than total logins!")

else:
  engagement_rate = (feature_uses / total_logins) * 100
  st.metric(label='Engagement Rate',value=f'{engagement_rate:.1f}%')

  if engagement_rate >= 50:
    st.success('**Power User !** 🚀 \n\n**Action:** Send them a prompt to leave an app store review.')

  elif engagement_rate >= 20:
    st.info('**Action User** 👍 \n\n**Action:** Send a tip on how to get more out the feature.')

  else:
    st.warning('**AT RISK** ⚠️ \n\n**Action:** Send a re-engagement email with a quick tutorial.')