# -*- coding: utf-8 -*-
"""Feature_Engagement_Scorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lW-iW1CZ39a9akTbaQmcjnmqDCoVE-A
"""

import streamlit as st

st.title('App Feature Engagement Scorer')
st.write('Calculate user engagement and get recommended actions based on feature usage')

# Variable Inputs
total_logins = st.number_input('Total App Logins (this week)', min_value=0,value=0,step=1)
feature_uses = st.number_input('New Feature Uses (this week)', min_value=0,value=0,step=1)

if st.button("Calculate Engagement"):

    # --- Section 4: The Logic & Output ---

    # 1. Edge Case Handling: Prevent dividing by zero
    if total_logins == 0:
        if feature_uses > 0:
            st.error("Wait a minute! A user can't use a feature without logging in. Check your data.")
        else:
            st.warning("No logins recorded. User is completely inactive.")

    # 2. Data Validation: Feature uses shouldn't exceed total logins
    elif feature_uses > total_logins:
        st.error("Data error: Feature uses cannot be greater than total logins!")

    # 3. The Core Logic
    else:
        # Calculate the rate
        engagement_rate = (feature_uses / total_logins) * 100

        # Display a nice dashboard metric
        st.metric(label="Engagement Rate", value=f"{engagement_rate:.1f}%")

        # Categorize the user based on the rate
        if engagement_rate >= 50:
            st.success("**Power User!** 🚀 \n\n**Action:** Send them a prompt to leave an app store review.")

        elif engagement_rate >= 20:
            st.info("**Active User** 👍 \n\n**Action:** Send a tip on how to get more out of the feature.")

        else:
            st.warning("**At Risk** ⚠️ \n\n**Action:** Send a re-engagement email with a quick tutorial.")