# -*- coding: utf-8 -*-
"""Product_Metrics_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPjsIvY1nW0m1K1nK-adYdyfnxoX93Xj
"""

import streamlit as st

st.set_page_config(page_title='Product Analyst Converter', page_icon='📊')

st.title('📊 Product Analyst Metric Converter')
st.write('Easily convert and estimate product metrics.')
st.markdown('---')

product_metric_list = ['Revenue','Agile Estimation','User Engagement']
convert_metric = st.selectbox(
    "Which type of conversion do you need to run?",
    ["Select a category...",
     "1. Revenue (MRR <-> ARR)",
     "2. Agile Estimation (Story Points -> Days)",
     "3. User Engagement (DAU <-> MAU proxy)"]
)


if convert_metric in product_metric_list:

  if convert_metric.lower() in ['revenue', 'revenue']:
    st.subheader('Revenue Conversion')
    direction = st.radio('Are you converting ARR or MRR?: ',['ARR','MRR','arr','mrr'])
    amount = st.number_input('Enter revenue amount: €', min_value=0.0, format='%.2f')

    if amount > 0:
      if direction.lower() in ['arr','arr']:
        arr = amount * 12
        st.success(f'**Result**: Your Annual Recurring Revenue (ARR) is **€{arr:,.2f}**')
      elif direction in ['M','m']:
        mrr = amount / 12
        st.success(f'**Result:** Your Monthly Recurring Revenue (MRR) is **€{mrr:,.2f}**')
      else:
        print('Error: Invalid revenue direction selected.')

  elif convert_metric.lower() in ['agile estimation', 'agile estimation']:
      st.subheader('Agile Estimation Conversion')
      points = st.number_input('Enter the number of Story Points from 1 to 8: ', min_value=1,step=1)
      seniority = st.selectbox('Is the developer "Junior","Mid-level", or "Senior"?: ', ['Junior','junior','Mid-level','mid-level','Senior','senior'])

      if seniority.lower() in ['junior','junior']:
        days = points * 2.0
        st.success(f'Result: Estimated Developer time is {days} days.')
      elif seniority.lower() in ['mid-level','mid-level']:
        days = points * 1.0
        st.success(f'Result: Estimated Developer time is {days} days.')
      elif seniority.lower() in ['senior','senior']:
        days = points * 0.5
        st.success(f'Result: Estimated Developer time is {days} days.')
      else:
        print('Error: Invalid seniorty level selected.')

  elif convert_metric.lower() in ['user engagement','user engagement']:
      st.subheader('User Engagement Story')
      direction = st.radio('Are you estimating MAU from DAU or DAU from MAU?: ',['MAU','mau','DAU','dau'])
      users = st.number_input('Enter the number of users: ', min_value=0, step=1)

      if users > 0:
        if direction.lower() in ['mau','mau','mau']:
          mau = users * 20
          st.success(f'**Result:** Your estimated Monthly Active Users (MAU) is **{mau:,}**')
        elif direction.lower() in ['dau','dau','dau']:
          dau = users / 30
          st.success(f'**Results:** Your estimated Daily Active Users (DAU) is **{int(dau):,}**')
        else:
          print('Error: Invalid engagement direction selected.')

  else:
    print(f'\nError: Invalid category selected. Please restart the program and choose one of the following options: {product_metric_list}')



print('\nThank you for using the Product Analyst Toolkit!')

