# -*- coding: utf-8 -*-
"""Product_Metrics_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPjsIvY1nW0m1K1nK-adYdyfnxoX93Xj
"""

import streamlit as st

st.set_page_config(page_title='Product Analyst Converter', page_icon='📊')

st.title('📊 Product Analyst Metric Converter')
st.write('Easily convert and estimate product metrics.')
st.markdown('---')

convert_metric = st.selectbox(
    "Which type of conversion do you need to run?",
    ["Select a category...",
     "1. Revenue (MRR <-> ARR)",
     "2. Agile Estimation (Story Points -> Days)",
     "3. User Engagement (DAU <-> MAU proxy)"]
)


if convert_metric == '1. Revenue (MRR <-> ARR)':
    st.subheader('Revenue Conversion')
    direction = st.radio('Are you converting ARR or MRR?: ',['ARR','MRR'])
    amount = st.number_input('Enter revenue amount: €', min_value=0.0, format='%.2f')

    if amount > 0:
      if direction == 'ARR':
        arr = amount * 12
        st.success(f'**Result**: Your Annual Recurring Revenue (ARR) is **€{arr:,.2f}**')
      elif direction == 'MRR':
        mrr = amount / 12
        st.success(f'**Result:** Your Monthly Recurring Revenue (MRR) is **€{mrr:,.2f}**')
      else:
        print('Error: Invalid revenue direction selected.')

elif convert_metric == '2. Agile Estimation (Story Points -> Days)':
      st.subheader('Agile Estimation Conversion')
      points = st.number_input('Enter the number of Story Points from 1 to 8: ', min_value=1,step=1)
      seniority = st.selectbox('Is the developer "Junior","Mid-level", or "Senior"?: ', ['Junior','junior','Mid-level','mid-level','Senior','senior'])

      if seniority == 'Junior':
        days = points * 2.0
        st.success(f'Result: Estimated Developer time is {days} days.')
      elif seniority == 'Mid-level':
        days = points * 1.0
        st.success(f'Result: Estimated Developer time is {days} days.')
      elif seniority == 'Senior':
        days = points * 0.5
        st.success(f'Result: Estimated Developer time is {days} days.')
      else:
        print('Error: Invalid seniorty level selected.')

elif convert_metric == '3. User Engagement (DAU <-> MAU proxy)':
      st.subheader('User Engagement Story')
      direction = st.radio('Are you estimating MAU from DAU or DAU from MAU?: ',['Estimate MAU', 'Estimate DAU'])
      users = st.number_input('Enter the number of users: ', min_value=0, step=1)

      if users > 0:
        if direction == 'Estimate MAU':
          mau = users * 20
          st.success(f'**Result:** Your estimated Monthly Active Users (MAU) is **{mau:,}**')
        elif direction == 'Estimate DAU':
          dau = users / 30
          st.success(f'**Results:** Your estimated Daily Active Users (DAU) is **{int(dau):,}**')
        else:
          print('Error: Invalid engagement direction selected.')

