# -*- coding: utf-8 -*-
"""User_Story_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ow7IlR0Oe2Nv-EfocDGiBaJWgfQNZaZ8
"""

import  streamlit as st
from fpdf import FPDF

# --- 1. STREAMLIT USER INTERFACE ---
st.title('Data User Story Generator 📊')
st.write('Fill out the fields below to generate and download a Data-focused User Story.')

# Create input fields for the user
role = st.text_input('As a... (e.g. Data Scientist, Product Analyst, Marketing Analyst, Downstream System)')
feature = st.text_input('I want to... (e.g. access a daily aggregated table of customer transcations)')
benefit = st.text_input('So that... (e.g. I can train my churn prediction Model)')

# Add a specific field for Data Quality / SLAs
data_requirements = st.text_input('Data & SLA Requirements (e.g., Refreshed hourly < 1% null values, GDPR compliant)')

# Create a larger text area for Acceptance Criteria
criteria = st.text_area('Acceptance Criteria (List what needs to happen for this to be "done"):')

#--- 2. APP LOGIC & PDF GENERATION ---
# When the user clicks this button, the indented code runs sequentially
if st.button('Generate Data User Story'):
  # Check if the user actually typed something in the main fields
  if role and feature and benefit:
    # Show a preview on the screen
    st.success('Data User Story Generated Successfully!')
    st.markdown(f'**As a** {role}, <br>--I want to** {feature}, <br>**so that** {benefit}.',unsafe_allow_html=True)

    #--- BUILDING THE PDF
    pdf = FPDF()
    pdf.add_page()

    # Set up the Title
    pdf.set_font('helvetica',"B",16)
    pdf.cell(0,10,'User Story Document',ln=True,align='C')
    pdf.ln(10)

    # Format and add the User Story statement
    pdf.set_font('helvetica', size=12)
    story_statement = f'As a {role},\nI want to {feature},\nSo that {benefit}.'
    pdf.multi_cell(0,10,story_statement)
    pdf.ln(5)

    # Add the Data Requirements sections (if the user filled it out)
    if data_requirements:
      pdf.set_font('helvetica',"B",12)
      pdf.cell(0,10,'Data & SLA Requirements:',ln=True)

      pdf.set_font('helvetica',size=12)
      pdf.multi_cell(0,10,data_requirements)
      pdf.ln(5)

      # Add the Acceptance Criteria section
      pdf.set_font('helvetica', 'B',12)
      pdf.cell(0,10,'Acceptance Criteria:',ln=True)

      pdf.set_font('helvetica',size=12)
      pdf.multi_cell(0,10,criteria)

      # Save the generated PDF data into a variable
      pdf_bytes = pdf.output()

      # Create the Streamlit download
      st.download_button(
          label='📄 Download Data User Story as PDF',
          data=bytes(pdf_bytes),
          file_name='User_story.pdf',
          mime='application/pdf'
      )
  else:
    st.error('Please fill in the Role, Feature, and Benefit fields to generate your user story')