# -*- coding: utf-8 -*-
"""User_Story_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ow7IlR0Oe2Nv-EfocDGiBaJWgfQNZaZ8
"""

import streamlit as st
from fpdf import FPDF

st.title('Data User Story Generator 📊')
st.write('Fill out the fields below to generate and download a Data-focused User Story.')

role = st.text_input('As a... (e.g. Data Scientist, Product Analyst, Marketing Analyst, Downstream System)')
feature = st.text_input('I want to... (e.g. access a daily aggregated table of customer transcations)')
benefit = st.text_input('So that... (e.g. I can train my churn prediction Model)')
data_requirements = st.text_input('Data & SLA Requirements (e.g., Refreshed hourly < 1% null values, GDPR compliant)')
criteria = st.text_area('Acceptance Criteria (List what needs to happen for this to be "done"):')


# --- 2. APP LOGIC & PDF GENERATION ---

# Initialize session state to hold our PDF data
if 'pdf_data' not in st.session_state:
    st.session_state.pdf_data = None

if st.button('Generate Data User Story'):
    if role and feature and benefit:
        st.success('Data User Story Generated Successfully!')
        st.markdown(f'**As a** {role}, <br>**I want to** {feature}, <br>**so that** {benefit}.', unsafe_allow_html=True)

        # --- BUILDING THE PDF ---
        pdf = FPDF()
        pdf.add_page()

        # Set up the Title
        pdf.set_font('helvetica', "B", 16)
        pdf.cell(0, 10, 'User Story Document', ln=True, align='C')
        pdf.ln(10)

        # Format and add the User Story statement
        pdf.set_font('helvetica', size=12)
        story_statement = f'As a {role},\nI want to {feature},\nSo that {benefit}.'
        pdf.multi_cell(0, 10, story_statement)
        pdf.ln(5)

        # Add the Data Requirements section (only if filled out)
        if data_requirements:
            pdf.set_font('helvetica', "B", 12)
            pdf.cell(0, 10, 'Data & SLA Requirements:', ln=True)
            pdf.set_font('helvetica', size=12)
            pdf.multi_cell(0, 10, data_requirements)
            pdf.ln(5)

        # Add the Acceptance Criteria section (Notice this is now un-indented!)
        if criteria:
            pdf.set_font('helvetica', 'B', 12)
            pdf.cell(0, 10, 'Acceptance Criteria:', ln=True)
            pdf.set_font('helvetica', size=12)
            pdf.multi_cell(0, 10, criteria)

        # Save the generated PDF data into Streamlit's memory
        pdf_bytes = pdf.output()
        st.session_state.pdf_data = pdf_bytes.encode('latin-1')

    else:
        st.error('Please fill in the Role, Feature, and Benefit fields to generate your user story.')

# --- 3. THE DOWNLOAD BUTTON ---
# This sits completely OUTSIDE the Generate button's block.
# If there is PDF data in the session state, show the download button.
if st.session_state.pdf_data is not None:
    st.download_button(
        label='📄 Download Data User Story as PDF',
        data=st.session_state.pdf_data,
        file_name='User_story.pdf',
        mime='application/pdf'
    )